### ISSUE TITLE
no dev task & invalid lock & no playground/react dir 

### ISSUE THREAD

**Issue by reggi** [cyco130/haydi#2]
➜  haydi git:(main) deno run cli/dev/dev.ts 
error: The source code is invalid, as it does not match the expected hash in the lock file.
  Specifier: https://esm.sh/@ampproject/remapping@2.2.0
  Lock file: /Users/thomasreggi/Documents/GitHub/haydi/deno.lock

**Comment by reggi** [comment]
this is hiding playground


	"files.exclude": {
		"playground/**": true
	},

**Comment by reggi** [comment]
sorry I think I got it but it's confusing, it's all within playground. 👍

**Comment by cyco130** [comment]
Hi!

You can delete the lock file for now and try again. It's not in a very "ready" state obviously 😅

I hid the playground on purpose so I can open it in a different window (VSCode didn't like separate `deno.json`s in the same workspace at the time, not sure if it's the same now).

**Comment by cyco130** [comment]
> VSCode didn't like separate `deno.json`s in the same workspace at the time, not sure if it's the same now

Still the same. The language server doesn't understand separate settings for separate directories.
